script: |
  # اذهب إلى مجلد البوت
  cd /root/bots/OKXBOT

  # تأكد من أنك تعمل كمستخدم لديه الصلاحيات المناسبة
  git config --global --add safe.directory /root/bots/OKXBOT

  # احصل على آخر التحديثات من GitHub
  git fetch --all

  # تجاهل أي تعديلات محلية وافرض نسخة GitHub (أكثر قوة من git pull)
  git reset --hard origin/main

  # فعّل البيئة الافتراضية بطريقة أكثر توافقية
  # واستدعِ pip مباشرة لضمان استخدام النسخة الصحيحة
  venv/bin/pip install -r requirements.txt

  # أعد تشغيل البوت بالتحديثات الجديدة
  pm2 reload OKX_Maestro_Bot
