# اسم الـ Workflow
name: Deploy Bot to VPS

# المشغلات: يعمل عند التحديث أو يدويًا
on:
  push:
    branches:
      - main
  workflow_dispatch:

# تعريف المهام (Jobs)
jobs:
  deploy:
    # بيئة التشغيل
    runs-on: ubuntu-latest
    
    # خطوات التنفيذ
    steps:
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_SSH_HOST }}
        username: ${{ secrets.VPS_SSH_USERNAME }}
        key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        
        # السكريبت المحسّن والكامل الذي سيتم تنفيذه على السيرفر
        script: |
          # اذهب إلى مجلد البوت
          cd /root/bots/OKXBOT

          # (اختياري ولكن موصى به) أمر لتجنب مشاكل صلاحيات git
          git config --global --add safe.directory /root/bots/OKXBOT

          # احصل على آخر التحديثات من GitHub
          git fetch --all

          # تجاهل أي تعديلات محلية وافرض نسخة GitHub (أكثر قوة من git pull)
          git reset --hard origin/main

          # فعّل البيئة الافتراضية بطريقة أكثر توافقية وثبّت المكتبات
          venv/bin/pip install -r requirements.txt

          # أعد تشغيل البوت بالتحديثات الجديدة
          pm2 reload OKX_Maestro_Bot
